cat("Loading necessary packages...\n")
library(ggplot2)
library(RMySQL)
library(ggplot2)
library(caret)
library(e1071)
library(pROC)
#library(forecast)
library(ggvis)
library(plyr)
library(dplyr)
library(gridExtra)
library(magrittr)
library(Hmisc)
cat("Packages loaded.\n")
cat("Welcome to Betlab Project!\n")
