cat("Loading necessary packages...\n")
library(ggplot2)
library(vioplot)
library(corrplot)
library(polycor)
library(RMySQL)
library(caret)
library(tidyr)
library(properties)
library(e1071)
library(pROC)
library(gridExtra)
library(magrittr)
library(MASS)
library(gbm)
library(bnclassify)
library(C50)
library(kernlab)
library(xgboost)
library(testthat)
library(Hmisc)
library(data.table)
library(plyr)
library(dplyr)
cat("Packages loaded.\n")

Sys.setenv(PROJECT_PATH = 'C:/RStudioWorkspace/Betlab/')
Sys.setenv(DATA_PATH = paste(Sys.getenv('PROJECT_PATH'), 'data/', sep = ''))
Sys.setenv(TESTS_PATH = paste(Sys.getenv('PROJECT_PATH'), 'tests/testthat/', sep = ''))
Sys.setenv(CORE_COUNT = 6)

# Logging
library(logging)
basicConfig()

source(file = 'C:/RStudioWorkspace/BetLab/scripts/scriptUtils.R', echo = FALSE, encoding = 'UTF-8')
source(file = 'C:/RStudioWorkspace/BetLab/featureEngineering/playerFormForecast.R', echo = FALSE, encoding = 'UTF-8')
source(file = 'C:/RStudioWorkspace/BetLab/featureEngineering/positionFeatureExtraction.R', echo = FALSE, encoding = 'UTF-8')
source(file = 'C:/RStudioWorkspace/BetLab/featureEngineering/adjGradeImputation.R', echo = FALSE, encoding = 'UTF-8')
source(file = 'C:/RStudioWorkspace/BetLab/featureEngineering/adjPriceForecast.R', echo = FALSE, encoding = 'UTF-8')
source(file = 'C:/RStudioWorkspace/BetLab/models/models.R', echo = FALSE, encoding = 'UTF-8')
source(file = 'C:/RStudioWorkspace/BetLab/interface/interface.R', echo = FALSE, encoding = 'UTF-8')
source(file = 'C:/RStudioWorkspace/BetLab/dataProvider/matchesDao.R', echo = FALSE, encoding = 'UTF-8')
source(file = 'C:/RStudioWorkspace/BetLab/dataProvider/playerStatDao.R', echo = FALSE, encoding = 'UTF-8')
source(file = 'C:/RStudioWorkspace/BetLab/dataProvider/loadData.R', echo = FALSE, encoding = 'UTF-8')
source(file = 'C:/RStudioWorkspace/BetLab/dataProvider/tuningProfileDao.R', echo = FALSE, encoding = 'UTF-8')
source(file = 'C:/RStudioWorkspace/BetLab/scripts/scriptUtils.R', echo = FALSE, encoding = 'UTF-8')
source(file = 'C:/RStudioWorkspace/BetLab/models/betMetrics.R', echo = FALSE, encoding = 'UTF-8')
loginfo('Source loaded.')

# Test execution
source(file = 'C:/RStudioWorkspace/Betlab/tests/executeTests.R', echo = FALSE, encoding = 'UTF-8')
loginfo('Running Tests')
executeAllTests()
loginfo("Welcome to Betlab Project!")
