install.packages('psych')
install.packages('ggplot2')
install.packages('caret')
install.packages('e1071')
install.packages('pROC')
install.packages('forecast')
install.packages('ggvis')
install.packages('gridExtra')
install.packages('magrittr')
install.packages('Hmisc')
install.packages("tidyr")
install.packages('dplyr')
library(forecast)
library(e1071)
library(dplyr)
library(Hmisc)
install.packages('RMySQL', type = 'source', verbose = TRUE, INSTALL_opts = c('--no-lock'))