---
title: "The Betlab Project"
author: "Tobias Diederich"
date: "Saturday, October 31, 2015"
output: html_document
---

## Abstract

Beating the booky with better predictions, that's the aim.
Using data from german Bundesliga 1, containing matches for seasons 2005-2015, lineups, players with marketprice history, grades for players who played, booky odds for each match and more. Using extreeme gradient boosting and tuning a model with maximum expected profit versus booky odds.

## Folder Structure

* dataProvider: contains functions to load the raw data and do some sata cleaning
* featureEngineering: contains functions to extract meaningfull features from the data
* models: contains functions to support on model tuning
* exploration: Exploration scripts for the raw data, engineered features and model tuning
* data: contains R Objects in Rds-files. 'BL1_2005-2015.Rds' provides all data used in exploration and documentation and makes everything reproduceable. All .Rds-files are generated and saved in the exploration scripts
* blog: Documentation and reports of the analysis process
* tests: Unit tests with testthat

## Documentation

See my blog [TODO] or the docs in blog-folder.