cat("Loading necessary packages...\n")
suppressMessages(library(ggplot2))
suppressMessages(library(vioplot))
suppressMessages(library(corrplot))
suppressMessages(library(polycor))
suppressMessages(library(RMySQL))
suppressMessages(library(caret))
suppressMessages(library(tidyr))
suppressMessages(library(properties))
suppressMessages(library(e1071))
suppressMessages(library(pROC))
suppressMessages(library(gridExtra))
suppressMessages(library(magrittr))
suppressMessages(library(MASS))
suppressMessages(library(gbm))
suppressMessages(library(bnclassify))
suppressMessages(library(C50))
suppressMessages(library(kernlab))
suppressMessages(library(xgboost))
suppressMessages(library(testthat))
suppressMessages(library(Hmisc))
suppressMessages(library(data.table))
suppressMessages(library(plyr))
suppressMessages(library(dplyr))
cat("Packages loaded.\n\n")

# Logging
suppressMessages(library(logging))
basicConfig()
loginfo('Logging initialized.')

source(file = 'C:/RStudioWorkspace/BetLab/scripts/scriptUtils.R', echo = FALSE, encoding = 'UTF-8')
source(file = 'C:/RStudioWorkspace/BetLab/featureEngineering/playerFormForecast.R', echo = FALSE, encoding = 'UTF-8')
source(file = 'C:/RStudioWorkspace/BetLab/featureEngineering/positionFeatureExtraction.R', echo = FALSE, encoding = 'UTF-8')
source(file = 'C:/RStudioWorkspace/BetLab/models/models.R', echo = FALSE, encoding = 'UTF-8')
source(file = 'C:/RStudioWorkspace/BetLab/interface/interfaceService.R', echo = FALSE, encoding = 'UTF-8')
loginfo('Source loaded.')